#!/bin/bash

set -uo pipefail

hash go &> /dev/null
[[ $? -ne 0 ]]\
    && echo "go toolchain is not installed"\
    && exit 2

namespace='git.spreadomat.net/sprd'
project_root="$(cd $(dirname $0)/.. && pwd)"
project_name="$(basename $project_root)"
full_path="$project_root/.go/src/$namespace/$project_name"

git submodule update --init && git submodule update --checkout

link_into_gopath() {
    echo "linking \"$project_root\" into local GOPATH: $full_path" &&\
    ln -s $project_root $full_path
}

mkdir -p $project_root/.go/src/$namespace
[[ -e "$full_path" ]] && [[ ! -L "$full_path" ]] &&\
    echo "\"$full_path\" already exists and is _not_ a symbolic link!" &&\
    exit 1

rm -f $full_path && link_into_gopath

pushd $project_root &>/dev/null
# fix go get for gopkg.in, see https://github.com/alecthomas/kingpin/issues/174
git config http.https://gopkg.in.followRedirects && GOPATH=$project_root/.go go get -d -v ./...
popd &>/dev/null

# vim: set syntax=sh
