#!/bin/bash

hash go &> /dev/null
[[ $? -ne 0 ]]\
    && echo "go toolchain is not installed"\
    && exit 2

project_root="$(cd $(dirname $0)/.. && pwd)"

source s/env

git submodule update --init && git submodule update --checkout

link_into_gopath() {
    echo "linking \"$project_root\" into local GOPATH: $full_path" &&\
    ln -s $project_root $full_path
}

mkdir -p $project_root/.go/src/$namespace
[[ -e "$full_path" ]] && [[ ! -L "$full_path" ]] &&\
    echo "\"$full_path\" already exists and is _not_ a symbolic link!" &&\
    exit 1

rm -f $full_path && link_into_gopath

# vim: set syntax=sh: